# Internal role variables and values that must NOT be overridden by the user.
#
# Variables defined here usually override earlier definitions due to the high
# precedence of this file. Each variable should have a concise comment above
# it, describing its purpose and how it fits into the role's functionality.

---

# List of facts used by the role (gathered on a best-effort basis if needed).
#
# To identify which subset a fact belongs to during development, you can use
# the following snippet:
#
# - ansible.builtin.setup:
#     gather_subset:
#       - '!min'
#       - '<subset_name, see parameter doc for details>'
__run_acmesh_used_facts:
  # from subset "distribution"
  - "distribution"
  - "distribution_major_version"
  - "distribution_version"
  - "os_family"


# List of platforms this role supports and was designed for.
#
# A warning will be issued if the list contains values and the role is executed
# on an unknown (not listed) platform, but execution will continue. Example:
#
# - name: "Fedora" # A ansible_facts value ('distribution' or 'os_family')
#   versions: # A ansible_facts value ('distribution_major_version' or
#     - "all" # 'distribution_version') or "all"
# - name: "Ubuntu"
#   versions:
#     - "22.04"
#     - "24.04"
# - name: "RedHat"
#   versions:
#     - "all"
# - name: "Debian"
#   versions:
#     - "all"
__run_acmesh_supported_platforms:
  - name: "Debian"
    versions:
      - "11"
      - "12"
  - name: "Fedora"
    versions:
      - "42"
      - "41"
  - name: "openSUSE Leap"
    versions:
      - "15.6"
  - name: "RedHat" # includes AlmaLinux, Rocky and CentOS Stream
    versions:
      - "9"
      - "10"
  - name: "Ubuntu"
    versions:
      - "24.04"
      - "22.04"


# List of package names to be installed when run_acmesh_state is
# set to "present".
__run_acmesh_packages_install:
  # We maintain this package list separately from the platform-specific
  # variables in this directory because these packages likely have the same
  # names across both supported platforms and unsupported, best-effort
  # platforms.
  #
  # For executing this role and/or Ansible itself
  - "git" # Download release form upstream
  # For acme.sh
  - "curl" # Communicate with the CA
  - "openssl"


# List of package names to be uninstalled when run_acmesh_state is
# set to "absent". This variable is useful when __run_acmesh_packages_install
# contains packages that are required for the managed software to function but
# should not be removed during uninstallation, as doing so could break other
# software. This is usually the case if there are common dependencies like
# "curl" or "openssl" which typically should remain installed even after
# uninstalling the software managed by this role.
__run_acmesh_packages_uninstall:
  [] # Remove the "[]" when adding values to this list.


# List of package names to be removed unconditionally before installation
# (e.g., to prevent conflicts or resolve incompatibilities).
__run_acmesh_packages_removal:
  [] # Remove the "[]" when adding values to this list.


# List of paths of files and directories to be removed unconditionally after
# installation. This is useful for removing default configuration resources
# that would otherwise create confusion or conflict with custom configurations
# managed by this role.
__run_acmesh_paths_removal:
  [] # Remove the "[]" when adding values to this list.


# String. Specifies the Git repository URL for acme.sh.
# This is used to fetch the acme.sh source code during installation or updates.
__run_acmesh_git_url: "https://github.com/acmesh-official/acme.sh.git"


# String. Defines the Git branch to use as "latest" if no specific version
# branch or tag is available.
# See the following for more information on "master" branch as latest:
# https://github.com/acmesh-official/acme.sh/issues/1162
__run_acmesh_git_fallback_version_branch: "master"


# String. URL of the GitHub API endpoint to fetch the latest acme.sh release
# information. This is used to determine the most recent version available
# for installation or updates.
__run_acmesh_githubapi_release_latest_url: "https://api.github.com/repos/acmesh-official/acme.sh/releases/latest"


# String. Path to the environment file sourced in /etc/profile.d/.
# This file ensures that acme.sh environment variables are set for all users.
__run_acmesh_profiled_envfile: "/etc/profile.d/acme.sh.env.sh"


# String. Path to the systemd service unit file for acme.sh certificate renewal.
# This defines the command and execution environment for automated certificate renewal.
__run_acmesh_systemd_renewal_servicefile: "/etc/systemd/system/acmesh-renewal.service"


# String. Path to the systemd timer unit file for acme.sh certificate renewal.
# This timer schedules the execution of the renewal service at regular intervals.
__run_acmesh_systemd_renewal_timerfile: "/etc/systemd/system/acmesh-renewal.timer"


# String. Path to the sha1sum executable.
__run_acmesh_sha1sum_executable: "/usr/bin/sha1sum"


### Override defaults of dependencies used by this role (if any).

# nothing right now
