# Internal role variables specific to: RedHat (os_family or distribution)
#
# Only values specific to the platform and its functionality should be included
# here. Variables in this file override those defined in vars/main.yml.
#
# Each variable should have a concise comment above it, describing its purpose
# and how it fits into the role's functionality.

---

# List of package names to be installed when run_acmesh_state is
# set to "present".
__run_acmesh_packages_install:
  # For executing this role and/or Ansible itself
  - "git" # Download release form upstream
  # For acme.sh
  - "curl" # Communicate with the CA
  - "openssl"
  # - "cronie": cron daemon and 'crontab' command
  #   Not used as a systemd timer is used instead.
  # - "oathtool": 2FA TOTP token generation
  #   Only needed for specific DNS challenge plugins. Since 2FA for DNS APIs is
  #   rarely used, we've opted not to install this package by default, despite
  #   its availability in standard repositories.
