# Internal role variables specific to: RedHat (os_family or distribution)
#
# Only values specific to the platform and its functionality should be included
# here. Variables in this file override those defined in vars/main.yml.
#
# Each variable should have a concise comment above it, describing its purpose
# and how it fits into the role's functionality.

---

# List of package names to be installed when run_acmesh_state is
# set to "present".
__run_acmesh_packages_install:
  # dependencies of this role or Ansible itself
  - "curl" # to determine latest version (playbook dependency)
  - "jq" # to determine latest version (playbook dependency)
  # dependencies of acme.sh
  - "cronie" # provides cron daemon and 'crontab' command
  - "git" # to get the upstream release
  - "oathtool" # to create 2FA TOTP tokens (e.g. needed for dns_inwx if 2FA is enabled)
  - "openssl"
