# Role argument validation.
#
# See defaults/main.yml for details on each variable. For more information on
# the argument_specs.yml format, refer to the official Ansible documentation:
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation

---

argument_specs:

  # foundata.acmesh/roles/run/tasks/main.yml entry point
  main:
    short_description: "Main entry point for the foundata.acmesh.run role"
    options:

      run_acmesh_state:
        type: "str"
        required: true
        choices:
          - "present"
          - "absent"

      run_acmesh_autoupgrade:
        type: "bool"
        required: true

      run_acmesh_autorenewal:
        type: "bool"
        required: true

      run_acmesh_environment:
        type: "dict"
        required: true

      run_acmesh_certs:
        type: "list"
        elements: "dict"
        required: true
        options:
          domains:
            type: "list"
            elements: "dict"
            options:
              name:
                type: "str"
              challenge:
                type: "dict"
                options:
                  type:
                    type: "str"
                    choices:
                      - "alpn"
                      - "dns"
                      - "standalone"
                      - "webroot"
                  dns_provider:
                    type: "str"
                  challenge_alias:
                    type: "str"
                  domain_alias:
                    type: "str"
                  httpport:
                    type: "int"
                  tlsport:
                    type: "int"
          install:
            type: "dict"
            options:
              ca_file:
                type: "str"
              cert_file:
                type: "str"
              fullcain_file:
                type: "str"
              key_file:
                type: "str"
              reloadcmd:
                type: "str"
          server:
            type: "str"
          force:
            type: "bool"
          debug:
            type: "bool"
          dnssleep:
            type: "int"
          pre_hook:
            type: "str"
          post_hook:
            type: "str"
          renew_hook:
            type: "str"
          extra_flags:
            type: "str"

      run_acmesh_user:
        type: "str"
        required: true

      run_acmesh_group:
        type: "str"
        required: true

      run_acmesh_cfg_accountemail:
        type: "str"
        required: true

      run_acmesh_cfg_home:
        type: "str"
        required: true

      run_acmesh_cfg_config_home:
        type: "str"
        required: true

      run_acmesh_cfg_cert_home:
        type: "str"
        required: true

      run_acmesh_cfg_logfile:
        type: "str"
        required: true

      run_acmesh_cfg_log_level:
        type: "int"
        required: true
        choices:
          - 1
          - 2

      run_acmesh_cfg_syslog:
        type: "int"
        required: true
        choices:
          - 0
          - 3
          - 6
          - 7
