# Setup: Manage basic resource removal, such as packages or service users.

---

- name: "Setup | Uninstall | Default | Call uninstall action of acme.sh"
  # The command module is used here. This approach is justified:
  #
  # - No built-in Ansible module provides a direct way to interact with acme.sh.
  # - Inline templating allows for safe and efficient parameter handling,
  #   avoiding the need for multiple additional tasks with little to no benefit.
  #
  # Notes on the command itself:
  #
  # See the official documentation for a explanation of the parameters:
  # https://github.com/acmesh-official/acme.sh/wiki/Options-and-Params
  ansible.builtin.command:
    cmd: >
      {{ run_acmesh_cfg_home }}/acme.sh
        --uninstall
        --config-home "{{ run_acmesh_cfg_config_home }}"
  args:
    removes: "{{ run_acmesh_cfg_home }}/acme.sh"
  when:
    - __run_acmesh_version_installed


- name: "Setup | Uninstall | Default | Remove packages"
  ansible.builtin.package:
    name: "{{ run_acmesh_packages_uninstall }}"
    state: "absent"
  when:
    - __run_acmesh_packages_uninstall is defined
    - (__run_acmesh_packages_uninstall | length) > 1


- name: "Setup | Uninstall | Default | Delete service user"
  ansible.builtin.user:
    name: "{{ run_acmesh_user }}"
    state: "absent"
    force: true
    remove: true # attempts to remove directories associated with the user (e.g. home)


- name: "Setup | Uninstall | Default | Delete service user's primary group"
  ansible.builtin.group:
    name: "{{ run_acmesh_user }}" # username == primary group name
    state: "absent"
    force: true


- name: "Setup | Uninstall | Disable acmesh-renewal.timer"
  ansible.builtin.systemd_service:
    name: "acmesh-renewal.timer"
    enabled: false


- name: "Setup | Uninstall | Default | Delete files and directories (except certificates)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "{{ run_acmesh_cfg_home }}"
    - "{{ run_acmesh_cfg_config_home }}"
    - "{{ run_acmesh_cfg_logfile }}"
    - "{{ __run_acmesh_profiled_envfile }}"
    - "{{ __run_acmesh_systemd_renewal_servicefile }}"
    - "{{ __run_acmesh_systemd_renewal_timerfile }}"





# FIXME / TODO delete additional, non-primary group for service user if it is empty
