# Default variables and values for this role.
#
# These variables are designed to be easily overridden (as they have a low
# precedence) and typically allow users to customize the role's behavior.
# Each variable should have a clear comment above it, describing its purpose
# and how it fits into the role's functionality.

---


run_acmesh_state: "present"

run_acmesh_autoupgrade: false

run_acmesh_autorenewal: true

run_acmesh_environment:
  {} # Remove the "{}" when adding values to this dict.

run_acmesh_certs:
  [] # Remove the "[]" when adding values to this list.

run_acmesh_user: "acmesh"

run_acmesh_group: "acmesh"

run_acmesh_cfg_accountemail: ""

run_acmesh_cfg_home: "/opt/acme.sh"

run_acmesh_cfg_config_home: "/etc/acme.sh"

run_acmesh_cfg_cert_home: "/var/opt/acme.sh"

run_acmesh_cfg_logfile: "/var/log/acme.sh.log"

run_acmesh_cfg_log_level: 1

run_acmesh_cfg_syslog: 3
