# Execute the collection role "run" against all driver-created instances (cleanup / absent)

- name: "Molecule | Cleanup | Include the foundata.acmesh.run role"
  ansible.builtin.include_role:
    name: "foundata.acmesh.run"
  vars:
    run_acmesh_state: "absent"
